/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coderbd.lms.view;

import com.coderbd.lms.domain.Book;
import com.coderbd.lms.domain.BookIssue;
import com.coderbd.lms.domain.BookReceive;
import com.coderbd.lms.domain.BookSummary;
import com.coderbd.lms.domain.Student;
import com.coderbd.lms.service.BookIssueService;
import com.coderbd.lms.service.BookReceiveService;
import com.coderbd.lms.service.BookService;
import com.coderbd.lms.service.BookSummaryService;
import com.coderbd.lms.service.StudentService;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rajail Islam
 */
public class LmsBookReceive extends javax.swing.JFrame {
    BookService bookService;
    private StudentService studentService;
    String bookID = "";
    String studentID = "";
    BookSummaryService bookSummaryService;
    BookReceiveService bookReceiveService;
    /**
     * Creates new form LmsDashboard
     */
    public LmsBookReceive() {
        initComponents();
         displayList();
        displayStudentList();
        displayDatasWithinTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBookId = new javax.swing.JComboBox<>();
        txtStudentId = new javax.swing.JComboBox<>();
        txtQty = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        lblMsg = new javax.swing.JLabel();
        btnReceive = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnAuthor = new javax.swing.JMenuItem();
        mnBookCategory = new javax.swing.JMenuItem();
        mnPurchaseBook = new javax.swing.JMenuItem();
        mnBookIssue = new javax.swing.JMenuItem();
        mnBookReceive = new javax.swing.JMenuItem();
        mnBookSummary = new javax.swing.JMenuItem();
        mnDepartment = new javax.swing.JMenuItem();
        mnEdition = new javax.swing.JMenuItem();
        mnInstitute = new javax.swing.JMenuItem();
        mnPublisher = new javax.swing.JMenuItem();
        mnSesson = new javax.swing.JMenuItem();
        mnShift = new javax.swing.JMenuItem();
        mnStudent = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Receieve | Library Management System");
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Library Management System");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("2017-18 All Rights Reserved. Library Management System");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 51));
        jLabel3.setText("Receive Book");

        jLabel4.setText("Book Name");

        jLabel5.setText("Student Name");

        jLabel6.setText("Qty");

        jLabel7.setText("Return Date");

        jLabel8.setText("Status");

        txtBookId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtBookIdItemStateChanged(evt);
            }
        });

        txtStudentId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtStudentIdItemStateChanged(evt);
            }
        });

        btnReceive.setText("Receive");
        btnReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveActionPerformed(evt);
            }
        });

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book ID", "Student ID", "Return Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblDisplay);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 412, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBookId, 0, 197, Short.MAX_VALUE)
                                        .addComponent(txtStudentId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtQty)
                                        .addComponent(txtReturnDate)
                                        .addComponent(txtStatus))
                                    .addComponent(btnReceive))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReceive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))))
        );

        jMenu4.setText("File");

        mnAuthor.setText("Author");
        mnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAuthorActionPerformed(evt);
            }
        });
        jMenu4.add(mnAuthor);

        mnBookCategory.setText("Book Category");
        mnBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookCategoryActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookCategory);

        mnPurchaseBook.setText("Purchase Book");
        mnPurchaseBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPurchaseBookActionPerformed(evt);
            }
        });
        jMenu4.add(mnPurchaseBook);

        mnBookIssue.setText("Book Issue ");
        mnBookIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookIssueActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookIssue);

        mnBookReceive.setText("Book Receive");
        mnBookReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookReceiveActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookReceive);

        mnBookSummary.setText("Book Summary");
        mnBookSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookSummaryActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookSummary);

        mnDepartment.setText("Department");
        mnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDepartmentActionPerformed(evt);
            }
        });
        jMenu4.add(mnDepartment);

        mnEdition.setText("Edition");
        mnEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditionActionPerformed(evt);
            }
        });
        jMenu4.add(mnEdition);

        mnInstitute.setText("Institute");
        mnInstitute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInstituteActionPerformed(evt);
            }
        });
        jMenu4.add(mnInstitute);

        mnPublisher.setText("Publisher");
        mnPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPublisherActionPerformed(evt);
            }
        });
        jMenu4.add(mnPublisher);

        mnSesson.setText("Sesson");
        mnSesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSessonActionPerformed(evt);
            }
        });
        jMenu4.add(mnSesson);

        mnShift.setText("Shift");
        mnShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnShiftActionPerformed(evt);
            }
        });
        jMenu4.add(mnShift);

        mnStudent.setText("Student");
        mnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudentActionPerformed(evt);
            }
        });
        jMenu4.add(mnStudent);

        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        jMenu4.add(mnUser);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu4.add(mnExit);

        menuBar.add(jMenu4);

        mnHelp.setText("Help");
        menuBar.add(mnHelp);

        mnLogout.setText("Logout");
        menuBar.add(mnLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookCategoryActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(true);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookCategoryActionPerformed

    private void mnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAuthorActionPerformed
        this.setVisible(false);

        new LmsAuthor().setVisible(true);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnAuthorActionPerformed

    private void mnPurchaseBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPurchaseBookActionPerformed
        this.setVisible(false);

        new LmsAuthor().setVisible(true);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnPurchaseBookActionPerformed

    private void mnBookIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookIssueActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(true);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookIssueActionPerformed

    private void mnBookReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookReceiveActionPerformed

        this.setVisible(true);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookReceiveActionPerformed

    private void mnBookSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookSummaryActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(true);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookSummaryActionPerformed

    private void mnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDepartmentActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(true);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnDepartmentActionPerformed

    private void mnEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditionActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(true);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnEditionActionPerformed

    private void mnInstituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInstituteActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(true);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnInstituteActionPerformed

    private void mnPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPublisherActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(true);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnPublisherActionPerformed

    private void mnSessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSessonActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(true);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnSessonActionPerformed

    private void mnShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnShiftActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(true);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnShiftActionPerformed

    private void mnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudentActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(true);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnStudentActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsDashboard().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(true);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnUserActionPerformed

    private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveActionPerformed
     
       
        int bid = Integer.parseInt(bookID);
        int stdID = Integer.parseInt(studentID);
        BookReceive rookReceive = new BookReceive(
                bid,
                stdID,
                txtReturnDate.getText(),
                Integer.parseInt(txtQty.getText()),
                txtStatus.getText()
        );

         bookReceiveService = new BookReceiveService();

        bookReceiveService.save(rookReceive);

        //for book summary
        
        Book book=bookService.getBookById(Integer.parseInt(bookID));
        
        
        
        bookSummaryService = new BookSummaryService();
  
        try {
            System.out.println("book.getBookCode()"+book.getBookCode());
            
       
            BookSummary bs = bookSummaryService.getBookSummaryByBookCode(book.getBookCode());
            if (bs != null) {
           //     if (bs.getBookCode().equals(book.getBookCode())) {



                    // after modification
                  
                    int nowAvailableQty = bs.getAvilableStock() + Integer.parseInt(txtQty.getText());
                    int nowAlreadyQty = bs.getAlreadyLend() - Integer.parseInt(txtQty.getText());
                    BookSummary bsx = new BookSummary(bs.getTotalStock(), nowAvailableQty, nowAlreadyQty);
                    bsx.setId(bs.getId());

                    bookSummaryService.update(bsx);

                    refreshTable();

             //   } 
            }
        } catch (Exception e) {
           e.printStackTrace();

        }

        refreshTable();
    }//GEN-LAST:event_btnReceiveActionPerformed

    private void txtBookIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtBookIdItemStateChanged
         String book = txtBookId.getItemAt(txtBookId.getSelectedIndex());
        bookID = book.split(",")[0];
    }//GEN-LAST:event_txtBookIdItemStateChanged

    private void txtStudentIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtStudentIdItemStateChanged
         String student = txtStudentId.getItemAt(txtStudentId.getSelectedIndex());
        studentID = student.split(",")[0];
    }//GEN-LAST:event_txtStudentIdItemStateChanged
 public void displayList() {
        bookService = new BookService();
        Set<Book> cList = bookService.getBookList();

        cList.forEach((c) -> {
            txtBookId.addItem(c.getId() + ", " + c.getName());

        });

    }

    public void displayStudentList() {
        studentService = new StudentService();
        Set<Student> cList = studentService.getStudentList();

        cList.forEach((c) -> {
            txtStudentId.addItem(c.getId() + ", " + c.getName());

        });

    }

    public void displayDatasWithinTable() {
         bookReceiveService=new BookReceiveService();
        List<BookReceive> pList = bookReceiveService.getList();
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        Object[] row = new Object[6];

        for (int i = 0; i < pList.size(); i++) {

            row[0] = pList.get(i).getId();
            row[1] = pList.get(i).getBookId();
            row[2] = pList.get(i).getStudentId();
            row[3] = pList.get(i).getReturnDate();
            row[4] = pList.get(i).getQty();
            row[5] = pList.get(i).getStatus();

            model.addRow(row);
        }

    }

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        model.setRowCount(0);
        displayDatasWithinTable();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LmsBookReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LmsBookReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LmsBookReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LmsBookReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LmsBookReceive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReceive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnAuthor;
    private javax.swing.JMenuItem mnBookCategory;
    private javax.swing.JMenuItem mnBookIssue;
    private javax.swing.JMenuItem mnBookReceive;
    private javax.swing.JMenuItem mnBookSummary;
    private javax.swing.JMenuItem mnDepartment;
    private javax.swing.JMenuItem mnEdition;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenuItem mnInstitute;
    private javax.swing.JMenu mnLogout;
    private javax.swing.JMenuItem mnPublisher;
    private javax.swing.JMenuItem mnPurchaseBook;
    private javax.swing.JMenuItem mnSesson;
    private javax.swing.JMenuItem mnShift;
    private javax.swing.JMenuItem mnStudent;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JComboBox<String> txtBookId;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JComboBox<String> txtStudentId;
    // End of variables declaration//GEN-END:variables
}
