/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coderbd.lms.view;

import com.coderbd.lms.domain.Institute;
import com.coderbd.lms.service.InstituteService;
import com.sun.java.swing.plaf.windows.WindowsBorders;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rajail Islam
 */
public class LmsInstitute extends javax.swing.JFrame {

    Institute institute;
    InstituteService instituteService;
    
    /**
     * Creates new form LmsDashboard
     */
    public LmsInstitute() {
        initComponents();
        displayInstituteWithinTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInstituteName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHouseNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRoadNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtblockOrVillage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtThana = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtInstituteType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAddressType = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comboDistrict = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboDivision = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        comboCountry = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShowInstituteInformation = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnAuthor = new javax.swing.JMenuItem();
        mnBookCategory = new javax.swing.JMenuItem();
        mnPurchaseBook = new javax.swing.JMenuItem();
        mnBookIssue = new javax.swing.JMenuItem();
        mnBookReceive = new javax.swing.JMenuItem();
        mnBookSummary = new javax.swing.JMenuItem();
        mnDepartment = new javax.swing.JMenuItem();
        mnEdition = new javax.swing.JMenuItem();
        mnInstitute = new javax.swing.JMenuItem();
        mnPublisher = new javax.swing.JMenuItem();
        mnSesson = new javax.swing.JMenuItem();
        mnShift = new javax.swing.JMenuItem();
        mnStudent = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Institute | Library Management System");
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Library Management System");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("2017-18 All Rights Reserved. Library Management System");

        jLabel3.setText("Institute Name:");

        txtInstituteName.setToolTipText("");

        jLabel4.setText("House No:");

        txtHouseNo.setToolTipText("");

        jLabel5.setText("Road No:");

        txtRoadNo.setToolTipText("");

        jLabel6.setText("Block/Village:");

        txtblockOrVillage.setToolTipText("");

        jLabel7.setText("Thana:");

        txtThana.setToolTipText("");

        jLabel10.setText("Institute Type:");

        txtInstituteType.setToolTipText("");

        jLabel8.setText("Address Type:");

        txtAddressType.setToolTipText("");

        jLabel9.setText("District:");

        comboDistrict.setEditable(true);
        comboDistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDistrict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setText("Division:");

        comboDivision.setEditable(true);
        comboDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDivision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setText("Country:");

        comboCountry.setEditable(true);
        comboCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 51));
        jLabel13.setText("Add Institute Information");

        tblShowInstituteInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "House No", "Road No", "Block/Village", "Thana", "District", "Division", "Country", "Address Type", "Institute Type"
            }
        ));
        tblShowInstituteInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShowInstituteInformationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblShowInstituteInformation);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDel.setText("Del");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 695, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(comboDivision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(comboDistrict, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtAddressType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtInstituteType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtThana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtblockOrVillage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtRoadNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtHouseNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtInstituteName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnDel)
                                .addGap(69, 69, 69)))
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInstituteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtRoadNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtblockOrVillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInstituteType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddressType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(btnDel)
                            .addComponent(btnAdd)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jMenu4.setText("File");

        mnAuthor.setText("Author");
        mnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAuthorActionPerformed(evt);
            }
        });
        jMenu4.add(mnAuthor);

        mnBookCategory.setText("Book Category");
        mnBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookCategoryActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookCategory);

        mnPurchaseBook.setText("Purchase Book");
        mnPurchaseBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPurchaseBookActionPerformed(evt);
            }
        });
        jMenu4.add(mnPurchaseBook);

        mnBookIssue.setText("Book Issue ");
        mnBookIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookIssueActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookIssue);

        mnBookReceive.setText("Book Receive");
        mnBookReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookReceiveActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookReceive);

        mnBookSummary.setText("Book Summary");
        mnBookSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookSummaryActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookSummary);

        mnDepartment.setText("Department");
        mnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDepartmentActionPerformed(evt);
            }
        });
        jMenu4.add(mnDepartment);

        mnEdition.setText("Edition");
        mnEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditionActionPerformed(evt);
            }
        });
        jMenu4.add(mnEdition);

        mnInstitute.setText("Institute");
        mnInstitute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInstituteActionPerformed(evt);
            }
        });
        jMenu4.add(mnInstitute);

        mnPublisher.setText("Publisher");
        mnPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPublisherActionPerformed(evt);
            }
        });
        jMenu4.add(mnPublisher);

        mnSesson.setText("Sesson");
        mnSesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSessonActionPerformed(evt);
            }
        });
        jMenu4.add(mnSesson);

        mnShift.setText("Shift");
        mnShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnShiftActionPerformed(evt);
            }
        });
        jMenu4.add(mnShift);

        mnStudent.setText("Student");
        mnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudentActionPerformed(evt);
            }
        });
        jMenu4.add(mnStudent);

        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        jMenu4.add(mnUser);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu4.add(mnExit);

        menuBar.add(jMenu4);

        mnHelp.setText("Help");
        menuBar.add(mnHelp);

        mnLogout.setText("Logout");
        menuBar.add(mnLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookCategoryActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(true);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);
        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookCategoryActionPerformed

    private void mnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAuthorActionPerformed
        this.setVisible(false);

        new LmsAuthor().setVisible(true);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnAuthorActionPerformed

    private void mnPurchaseBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPurchaseBookActionPerformed
        this.setVisible(false);

        new LmsAuthor().setVisible(true);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnPurchaseBookActionPerformed

    private void mnBookIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookIssueActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(true);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookIssueActionPerformed

    private void mnBookReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookReceiveActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(true);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookReceiveActionPerformed

    private void mnBookSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookSummaryActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(true);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookSummaryActionPerformed

    private void mnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDepartmentActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(true);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnDepartmentActionPerformed

    private void mnEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditionActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(true);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnEditionActionPerformed

    private void mnInstituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInstituteActionPerformed

        this.setVisible(true);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnInstituteActionPerformed

    private void mnPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPublisherActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(true);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnPublisherActionPerformed

    private void mnSessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSessonActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(true);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnSessonActionPerformed

    private void mnShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnShiftActionPerformed
       this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(true);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnShiftActionPerformed

    private void mnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudentActionPerformed
       this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(true);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnStudentActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
       this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(true);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnUserActionPerformed

    private void tblShowInstituteInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShowInstituteInformationMouseClicked
        // TODO add your handling code here:

        int row = tblShowInstituteInformation.getSelectedRow();
        TableModel model = tblShowInstituteInformation.getModel();

        txtInstituteName.setText(model.getValueAt(row, 1).toString());
        txtHouseNo.setText(model.getValueAt(row, 2).toString());
        txtRoadNo.setText(model.getValueAt(row, 3).toString());
        txtblockOrVillage.setText(model.getValueAt(row, 4).toString());
        txtThana.setText(model.getValueAt(row, 5).toString());
        comboDistrict.setSelectedItem(model.getValueAt(row, 6).toString());
        comboDivision.setSelectedItem(model.getValueAt(row, 7).toString());
        comboCountry.setSelectedItem(model.getValueAt(row, 8).toString());
        txtAddressType.setText(model.getValueAt(row, 9).toString());
        txtInstituteType.setText(model.getValueAt(row, 10).toString());

    }//GEN-LAST:event_tblShowInstituteInformationMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        institute = new Institute(
                txtInstituteName.getText(),
                txtHouseNo.getText(),
                txtRoadNo.getText(),
                txtblockOrVillage.getText(),
                txtThana.getText(),
                comboDistrict.getSelectedItem().toString(),
                comboDivision.getSelectedItem().toString(),
                comboCountry.getSelectedItem().toString(),
                txtAddressType.getText(),
                txtInstituteType.getText()
        );

        instituteService = new InstituteService();
        instituteService.save(institute);
        refreshTable();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        
        institute = new Institute(
                txtInstituteName.getText(),
                txtHouseNo.getText(),
                txtRoadNo.getText(),
                txtblockOrVillage.getText(),
                txtThana.getText(),
                comboDistrict.getSelectedItem().toString(),
                comboDivision.getSelectedItem().toString(),
                comboCountry.getSelectedItem().toString(),
                txtAddressType.getText(),
                txtInstituteType.getText()
        );

        int row = tblShowInstituteInformation.getSelectedRow();
        TableModel model = tblShowInstituteInformation.getModel();
        institute.setId(Integer.parseInt(model.getValueAt(row, 0).toString()));

        instituteService = new InstituteService();
        instituteService.update(institute);
        refreshTable();
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed

        
        institute = new Institute();
        instituteService = new InstituteService();

        int row = tblShowInstituteInformation.getSelectedRow();
        TableModel model = tblShowInstituteInformation.getModel();
        institute.setId(Integer.parseInt(model.getValueAt(row, 0).toString()));

        instituteService.delete(institute.getId());
        refreshTable();
        
    }//GEN-LAST:event_btnDelActionPerformed

    
    public void displayInstituteWithinTable() {
        instituteService = new InstituteService();
        List<Institute> pList = instituteService.getList();
        DefaultTableModel model = (DefaultTableModel) tblShowInstituteInformation.getModel();
        Object[] row = new Object[11];

        for (int i = 0; i < pList.size(); i++) {
            row[0] = pList.get(i).getId();
            row[1] = pList.get(i).getName();
            row[2] = pList.get(i).getHouseNo();
            row[3] = pList.get(i).getRoadNo();
            row[4] = pList.get(i).getBlockOrVillage();
            row[5] = pList.get(i).getThana();
            row[6] = pList.get(i).getDistrict();
            row[7] = pList.get(i).getDivision();
            row[8] = pList.get(i).getCountry();
            row[9] = pList.get(i).getAddresstype();
            row[10] = pList.get(i).getInstituteType();
            model.addRow(row);
        }

    }
    
    
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblShowInstituteInformation.getModel();
        model.setRowCount(0);
        displayInstituteWithinTable();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LmsInstitute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LmsInstitute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LmsInstitute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LmsInstitute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LmsInstitute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> comboCountry;
    private javax.swing.JComboBox<String> comboDistrict;
    private javax.swing.JComboBox<String> comboDivision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnAuthor;
    private javax.swing.JMenuItem mnBookCategory;
    private javax.swing.JMenuItem mnBookIssue;
    private javax.swing.JMenuItem mnBookReceive;
    private javax.swing.JMenuItem mnBookSummary;
    private javax.swing.JMenuItem mnDepartment;
    private javax.swing.JMenuItem mnEdition;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenuItem mnInstitute;
    private javax.swing.JMenu mnLogout;
    private javax.swing.JMenuItem mnPublisher;
    private javax.swing.JMenuItem mnPurchaseBook;
    private javax.swing.JMenuItem mnSesson;
    private javax.swing.JMenuItem mnShift;
    private javax.swing.JMenuItem mnStudent;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JTable tblShowInstituteInformation;
    private javax.swing.JTextField txtAddressType;
    private javax.swing.JTextField txtHouseNo;
    private javax.swing.JTextField txtInstituteName;
    private javax.swing.JTextField txtInstituteType;
    private javax.swing.JTextField txtRoadNo;
    private javax.swing.JTextField txtThana;
    private javax.swing.JTextField txtblockOrVillage;
    // End of variables declaration//GEN-END:variables
}
